# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - thomasvincent

# A list of assignees, overrides reviewers if set
assignees:
  - thomasvincent

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
  - draft

# A list of users to be skipped by both the reviewers and assignees
skipUsers:
  - dependabot[bot]

# Set to true to assign PR author as the assignee (in addition to thomasvincent)
addAssigneesAuthor: true