repository:
  name: cloudflare-ufw-sync
  description: A tool to synchronize Cloudflare IP ranges with UFW firewall rules
  homepage: https://github.com/thomasvincent/cloudflare-ufw-sync
  topics: cloudflare, ufw, firewall, security, python
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: python
    color: 3572A5
    description: Python related changes
  - name: ci
    color: 4a92e4
    description: Changes to CI/CD pipeline

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: ["CI"]
      enforce_admins: false
      restrictions:
        users: []
        teams: []

# Configure PR settings
pullRequests:
  defaultAssignees:
    - thomasvincent
  defaultReviewers:
    - thomasvincent