version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ~/.config/cloudflare-ufw-sync:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - CONFIG_PATH=/config/config.yaml
    command: "--config /config/config.yaml"